# Generated by Django 3.1.1 on 2020-09-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='pic',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
