# Generated by Django 3.1.1 on 2020-09-24 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_fileupload_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='title',
        ),
    ]
