# Generated by Django 3.1.1 on 2020-09-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_remove_fileupload_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='pic',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
